import { test } from 'node:test';
import assert from 'node:assert/strict';
import { Readable } from 'node:stream';
import { generateKeyPairSync, sign } from 'node:crypto';
import { createAnalyzeHandler } from '../server/analyze.mjs';
import { createTokenVerifier, HttpError } from '../server/firebase-token.mjs';
import { validateAnalysis } from '../server/analysis-schema.mjs';
const essay='Students can learn effectively by practising every day. '.repeat(40).trim();
const input={question:'Do you agree that regular practice improves learning?',essay};
function report(){const c={score:6.5,explanation:'Идеялар түсінікті.',strengths:['Ұстанымы анық.'],improvements:['Мысалды нақтыла.']};return {summary:'Жауап сұраққа сай келеді.',criteria:{TR:{...c},CC:{...c},LR:{...c},GRA:{...c}},structure:{introduction:'Кіріспе бар.',body:'Дәлел қос.',conclusion:'Қорытынды жаса.',cohesion:'Байланысын жақсарт.'},corrections:[],vocabulary:[],targets:Array.from({length:3},()=>({title:'Мысал',action:'Нақты мысал қос.',example:'For example, practice improves recall.'})),revisedParagraph:{original:'Students can learn effectively by practising every day.',improved:'Daily practice can make learning more effective.',explanation:'Қайталауды азайт.'},warnings:[]}}
const completion=data=>new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(data)}}]}),{status:200});
function setup(options={}){let request;const handler=createAnalyzeHandler({verifyToken:async token=>{if(token==='bad')throw new HttpError(401,'Invalid token');return token},getKey:()=> 'server-secret',fetchImpl:async(url,init)=>{request={url,init};return completion(report())},...options});return {handler,getRequest:()=>request}}
async function call(handler,{body=input,token='student',method='POST',headers={},raw}={}){const req=Readable.from([raw??JSON.stringify(body)]);req.method=method;req.headers={'content-type':'application/json',...(token?{authorization:`Bearer ${token}`} : {}),...headers};const res={statusCode:0,headers:{},setHeader(k,v){this.headers[k]=v},end(data){this.body=JSON.parse(data)}};await handler(req,res);return res}
test('successful analysis uses server secret, strict schema, and computed band',async()=>{const {handler,getRequest}=setup();const res=await call(handler);assert.equal(res.statusCode,200);assert.equal(res.body.overallBand,6.5);assert.equal(res.headers['Cache-Control'],'no-store');assert.ok(!JSON.stringify(res.body).includes('server-secret'));const req=getRequest();assert.equal(req.url,'https://api.groq.com/openai/v1/chat/completions');assert.equal(req.init.headers.Authorization,'Bearer server-secret');const payload=JSON.parse(req.init.body);assert.equal(payload.response_format.json_schema.strict,true);assert.equal(JSON.parse(payload.messages[1].content).essay,essay)});
test('missing authentication rejected before provider call',async()=>{const {handler,getRequest}=setup();assert.equal((await call(handler,{token:null})).statusCode,401);assert.equal(getRequest(),undefined)});
test('invalid authentication rejected',async()=>assert.equal((await call(setup().handler,{token:'bad'})).statusCode,401));
test('missing API key returns actionable error',async()=>assert.equal((await call(setup({getKey:()=>''}).handler)).statusCode,503));
test('GET is not supported',async()=>assert.equal((await call(setup().handler,{method:'GET'})).statusCode,405));
test('non-JSON content is rejected',async()=>assert.equal((await call(setup().handler,{headers:{'content-type':'text/plain'}})).statusCode,415));
test('broken JSON is rejected',async()=>assert.equal((await call(setup().handler,{raw:'{broken'})).statusCode,400));
test('oversized request is rejected',async()=>assert.equal((await call(setup().handler,{headers:{'content-length':'60001'}})).statusCode,413));
test('invalid question and short/long essays rejected',async()=>{for(const body of [{...input,question:'Hi'},{...input,essay:'Hi'},{...input,essay:'word '.repeat(1501)},{essay:42,question:'valid question'}])assert.equal((await call(setup().handler,{body})).statusCode,400)});
test('Groq key errors never expose provider body',async()=>{const h=setup({fetchImpl:async()=>new Response('provider-secret',{status:401})}).handler;const r=await call(h);assert.equal(r.statusCode,503);assert.ok(!JSON.stringify(r.body).includes('provider-secret'))});
test('Groq throttling returns retry information',async()=>{const r=await call(setup({fetchImpl:async()=>new Response('',{status:429})}).handler);assert.equal(r.statusCode,429);assert.equal(r.headers['Retry-After'],'30')});
test('provider timeout returns 504',async()=>{assert.equal((await call(setup({fetchImpl:async()=>{throw new DOMException('timed out','TimeoutError')}}).handler)).statusCode,504)});
test('truncated and malformed model outputs rejected',async()=>{for(const response of [new Response(JSON.stringify({choices:[{finish_reason:'length',message:{content:'{}'}}]})),new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:'not json'}}]})),completion({summary:'incomplete'})]){assert.equal((await call(setup({fetchImpl:async()=>response}).handler)).statusCode,502)}});
test('invented quotes and out-of-range scores are rejected',()=>{const r=report();assert.equal(validateAnalysis(r,essay),true);r.revisedParagraph.original='This sentence never appears.';assert.equal(validateAnalysis(r,essay),false);r.revisedParagraph.original='';r.criteria.TR.score=10;assert.equal(validateAnalysis(r,essay),false)});
test('successful request imposes cooldown, other user is independent',async()=>{const {handler}=setup();assert.equal((await call(handler)).statusCode,200);assert.equal((await call(handler)).statusCode,429);assert.equal((await call(handler,{token:'another-student'})).statusCode,200)});
test('concurrent requests for same user rejected',async()=>{let release;const {handler}=setup({fetchImpl:()=>new Promise(r=>{release=()=>r(completion(report()))})});const first=call(handler);while(!release)await new Promise(r=>setImmediate(r));assert.equal((await call(handler)).statusCode,429);release();assert.equal((await first).statusCode,200)});
test('failed request can be retried',async()=>{let attempts=0;const {handler}=setup({fetchImpl:async()=>++attempts===1?new Response('',{status:500}):completion(report())});assert.equal((await call(handler)).statusCode,502);assert.equal((await call(handler)).statusCode,200)});
const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048});
function token(overrides={},headerOverrides={}){const timestamp=Math.floor(Date.now()/1000);const header=Buffer.from(JSON.stringify({alg:'RS256',kid:'test',...headerOverrides})).toString('base64url');const payload=Buffer.from(JSON.stringify({aud:'ieltsplatform-ee25e',iss:'https://securetoken.google.com/ieltsplatform-ee25e',sub:'student-a',exp:timestamp+3600,iat:timestamp,auth_time:timestamp,...overrides})).toString('base64url');const data=header+'.'+payload;return data+'.'+sign('RSA-SHA256',Buffer.from(data),privateKey).toString('base64url')}
const verifier=()=>createTokenVerifier(async()=>new Response(JSON.stringify({test:publicKey.export({type:'spki',format:'pem'})}),{headers:{'cache-control':'max-age=3600'}}));
test('Firebase JWT signature, project, and expiry validated',async()=>{const verify=verifier();assert.equal(await verify(token()),'student-a');for(const t of [token({aud:'other-project'}),token({exp:1}),token({sub:''}),token({}, {alg:'none'}),token({}, {kid:'unknown'}),token().slice(0,-12)+'AAAAAAAAAAAA'])await assert.rejects(()=>verify(t),e=>e.status===401)});
test('Firebase cert outage fails closed',async()=>{const verify=createTokenVerifier(async()=>new Response('',{status:500}));await assert.rejects(()=>verify(token()),e=>e.status===503)});
