import { useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { addDoc, collection, serverTimestamp } from 'firebase/firestore';
import { useAuth } from './auth';
import { useContent } from './content';
import { db, errorMessage } from './firebase';
export default function ActivityCreate(){const {user,profile}=useAuth();const lessons=useContent('lessons');const navigate=useNavigate();const [title,setTitle]=useState(''),[lessonId,setLessonId]=useState(''),[kind,setKind]=useState('quiz'),[questions,setQuestions]=useState([{q:'',options:['','',''],correct:0,why:''},{q:'',options:['','',''],correct:0,why:''}]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(e:FormEvent){e.preventDefault();if(!user||profile?.role!=='teacher')return;setBusy(true);setError('');try{if(questions.some(q=>new Set(q.options.map(x=>x.trim())).size!==3))throw Error('Әр сұрақта үш түрлі жауап болуы керек.');const ref=await addDoc(collection(db,'activities'),{title:title.trim(),lessonId,kind,questions:questions.map(q=>({q:q.q.trim(),options:q.options.map(x=>x.trim()),answer:q.options[q.correct].trim(),why:q.why.trim()})),createdBy:user.uid,createdAt:serverTimestamp()});navigate('/tasks/'+ref.id)}catch(e){setError(e instanceof Error&&!('code' in e)?e.message:errorMessage(e))}finally{setBusy(false)}}
 if(profile?.role!=='teacher')return <p className="container page">Бұл бет мұғалімге арналған.</p>;
 return <section className="container article page"><Link to="/tasks">← Тапсырмалар</Link><h1>Интерактивті тапсырма қосу</h1><form onSubmit={save}><fieldset className="content-fields" disabled={busy}><label className="field">Тапсырма атауы<input required maxLength={300} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field">Сабақпен байланыстыру<select value={lessonId} onChange={e=>setLessonId(e.target.value)}><option value="">Жалпы жаттығу</option>{lessons.items.map(l=><option key={l.id} value={l.id}>{l.number}. {l.title}</option>)}</select></label><label className="field">Тапсырма түрі<select value={kind} onChange={e=>setKind(e.target.value)}>{[['quiz','Викторина'],['matching','Сәйкестендіру'],['gaps','Бос орынды толтыру'],['sorting','Идеяларды топтастыру'],['editing','Қатені түзету']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>{questions.map((q,i)=><section className="learning-panel" key={i}><h2>{i+1}-сұрақ</h2><label className="field">Сұрақ<textarea required maxLength={2000} value={q.q} onChange={e=>setQuestions(v=>v.map((x,j)=>j===i?{...x,q:e.target.value}:x))}/></label>{q.options.map((a,k)=><label className="field" key={k}>{k+1}-жауап<input required maxLength={500} value={a} onChange={e=>setQuestions(v=>v.map((x,j)=>j===i?{...x,options:x.options.map((y,n)=>n===k?e.target.value:y)}:x))}/></label>)}<label className="field">Дұрыс жауап<select value={q.correct} onChange={e=>setQuestions(v=>v.map((x,j)=>j===i?{...x,correct:Number(e.target.value)}:x))}>{q.options.map((_,k)=><option key={k} value={k}>{k+1}-жауап</option>)}</select></label><label className="field">Түсіндірме<textarea required maxLength={3000} value={q.why} onChange={e=>setQuestions(v=>v.map((x,j)=>j===i?{...x,why:e.target.value}:x))}/></label></section>)}{(error||lessons.error)&&<p role="alert">{error||lessons.error}</p>}<button className="button" disabled={busy||!!lessons.error}>Базаға сақтау</button></fieldset></form></section>
}
