import { courseLessons } from "./course";
export const prompts = [
{"id": "course-foundation", "category": "Негіздер", "type": "Opinion essay", "title": "Алғашқы диагностика", "prompt": "Some people believe that schools should teach practical life skills as well as academic subjects. To what extent do you agree or disagree?"},
{"id": "course-discussion", "category": "Discussion", "type": "Discussion essay", "title": "Жеке оқу немесе топтық оқу", "prompt": "Some people think students learn better alone, while others prefer group study. Discuss both views and give your own opinion."},
{"id": "course-opinion", "category": "Opinion", "type": "Opinion essay", "title": "Онлайн сабақтар", "prompt": "All secondary school lessons should be delivered online. To what extent do you agree or disagree?"},
{"id": "course-money", "category": "Opinion", "type": "Opinion essay", "title": "Қаржылық сауаттылық", "prompt": "Schools should teach students how to manage money. To what extent do you agree or disagree?"},
{"id": "course-advantages", "category": "Advantages / Disadvantages", "type": "Advantages & disadvantages", "title": "Қалаға көшу", "prompt": "More young people are moving to large cities. Do the advantages of this trend outweigh the disadvantages?"},
{"id": "course-remote", "category": "Advantages / Disadvantages", "type": "Advantages & disadvantages", "title": "Үйден жұмыс істеу", "prompt": "Many employees now work from home. Do the advantages of this development outweigh the disadvantages?"},
{"id": "course-problem", "category": "Problem / Solution", "type": "Problem & solution", "title": "Қаладағы кептеліс", "prompt": "Traffic congestion is increasing in many cities. What are the causes of this problem, and what solutions can you suggest?"},
{"id": "course-sleep", "category": "Problem / Solution", "type": "Problem & solution", "title": "Жасөспірімдердің ұйқысы", "prompt": "Many teenagers do not get enough sleep. What are the causes of this problem, and what measures could help address it?"},
{"id": "course-two-part", "category": "Two-Part Question", "type": "Two-part question", "title": "Тіл үйрену жолдары", "prompt": "Many people learn a foreign language. Why do they choose to do this? What is the most effective way to learn a language?"},
{"id": "course-news", "category": "Two-Part Question", "type": "Two-part question", "title": "Әлеуметтік желідегі жаңалықтар", "prompt": "Many young people prefer to get news through social media. Why is this the case? Is this a positive or negative development?"},
{"id": "course-mixed", "category": "Аралас практика", "type": "Opinion essay", "title": "Тегін қоғамдық көлік", "prompt": "Public transport should be free for everyone. To what extent do you agree or disagree?"},
{"id": "course-final", "category": "Финалдық сынақ", "type": "Opinion essay", "title": "Финалдық Writing Task 2 сынағы", "prompt": "Some people believe that secondary schools should give more time to practical skills than to academic subjects. To what extent do you agree or disagree?"},
{id:'education-1',category:'Білім',type:'Opinion essay',title:'Технология және білім',prompt:'Some people believe that technology makes learning more effective, while others think it distracts students. To what extent do you agree or disagree that technology improves education?'},
{id:'environment-1',category:'Экология',type:'Discussion essay',title:'Табиғатты кім қорғайды?',prompt:'Some people think that protecting the environment is the responsibility of governments, while others believe that individuals should take responsibility. Discuss both views and give your own opinion.'},
{id:'society-1',category:'Қоғам',type:'Advantages & disadvantages',title:'Үлкен қаладағы өмір',prompt:'More and more young people are moving from rural areas to cities. What are the advantages and disadvantages of this trend?'},
{id:'education-2',category:'Білім',type:'Discussion essay',title:'Үй тапсырмасының маңызы',prompt:'Some people believe that schoolchildren should not be given homework, while others argue that homework plays an important role in education. Discuss both views and give your own opinion.'},
{id:'technology-1',category:'Технология',type:'Problem & solution',title:'Экран алдындағы уақыт',prompt:'Many teenagers spend too much time using smartphones. What problems does this cause, and what measures could be taken to address them?'},
{id:'society-2',category:'Қоғам',type:'Two-part question',title:'Жаңа тілді үйрену',prompt:'Many people choose to learn a foreign language. Why do people decide to learn another language? What is the most effective way to learn one?'},
];
export const lessons = courseLessons;
export const criteria = ['Task Response','Coherence & Cohesion','Lexical Resource','Grammar & Accuracy'];
