import { localeTag } from './i18n';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth, Loader } from './auth';
import { useContent } from './content';
import { useRows, result, mean, ordered, focusNames, type Progress, type Attempt, type Activity, type LearningEssay } from './learningData';
import AccountDeletion from './AccountDeletion';
function score(e:LearningEssay){return mean(e.scores)?.toFixed(1)||'Баға жоқ'}
export default function LearningDashboard(){const {user,profile}=useAuth();const teacher=profile?.role==='teacher';const owner=teacher?undefined:user?.uid||null;const essays=useRows<LearningEssay>('essays',owner,teacher?['status','reviewed']:undefined);const queue=useRows<LearningEssay>('essays',teacher?undefined:null,['status','submitted']);const progress=useRows<Progress>('lessonProgress',owner);const attempts=useRows<Attempt>('activityAttempts',owner);const activities=useRows<Activity>('activities');const students=useRows<{id:string;name:string;role:string}>('users',teacher?undefined:null,['role','student']);const lessons=useContent('lessons');const prompts=useContent('prompts');const [student,setStudent]=useState(''),[filter,setFilter]=useState('all');
 const errors=[essays.error,queue.error,progress.error,attempts.error,activities.error,students.error,lessons.error,prompts.error].filter(Boolean);const loading=[essays,queue,progress,attempts,activities,students,lessons,prompts].some(v=>v.loading);if(loading)return <Loader/>;
 const all=teacher?[...essays.items,...queue.items]:essays.items;const visible=ordered(all.filter(e=>!student||e.ownerId===student));const reviews=visible.filter(e=>e.status==='reviewed'&&e.scores.length===4);const course=lessons.items.filter(l=>/^course-\d+$/.test(l.id));const selectedProgress=progress.items.filter(p=>!student||p.ownerId===student);const completed=selectedProgress.filter(p=>p.completed&&course.some(l=>l.id===p.lessonId));const ownAttempts=attempts.items.filter(a=>!student||a.ownerId===student);const passed=new Set(ownAttempts.filter(a=>a.submitted&&activities.items.some(t=>t.id===a.activityId&&result(a,t)===t.questions.length)).map(a=>a.ownerId+'_'+a.activityId));const criterionMeans=focusNames.map((_,i)=>reviews.length?reviews.reduce((n,e)=>n+e.scores[i],0)/reviews.length:null);const weakest=criterionMeans.every(v=>v===null)||new Set(criterionMeans).size===1?null:criterionMeans.indexOf(Math.min(...criterionMeans.filter((v):v is number=>v!==null)));const next=course.find(l=>!completed.some(p=>p.lessonId===l.id));const targets=reviews.length?reviews[reviews.length-1].goals||[]:[];
 const groups=new Map<string,LearningEssay[]>();visible.forEach(e=>{const key=e.rootId||e.id;groups.set(key,[...(groups.get(key)||[]),e])});const diagnostic=reviews.find(e=>e.mode==='diagnostic');const final=[...reviews].reverse().find(e=>e.mode==='mock');const xp=completed.length*10+passed.size*10+visible.filter(e=>e.plan&&Object.values(e.plan).every(v=>v.trim())).length*15+visible.filter(e=>e.status!=='draft').reduce((n,e)=>n+(e.mode==='mock'?50:e.parentId?30:30),0);
 const focusCounts=focusNames.map(f=>reviews.filter(e=>e.focus?.includes(f)).length);const badges=[visible.some(e=>e.status!=='draft')?'Алғашқы эссе':null,visible.some(e=>e.parentId&&e.status==='reviewed')?'Қайта жазу шебері':null,course.length>0&&completed.length===course.length&&!teacher?'Курс аяқталды':null,final?'Финалдық сынақ тапсырылды':null].filter(Boolean);
 return <section className="container page"><h1>{teacher?'Мұғалім кабинеті':'Менің оқу жолым'}</h1>{errors.map((e,i)=><p className="notice error" role="alert" key={i}>{e}</p>)}{errors.length>0?<p>Есепті толық көрсету үшін деректерді жүктеу қатесін түзетіңіз.</p>:<>{teacher&&<><label className="field">Оқушы<select value={student} onChange={e=>setStudent(e.target.value)}><option value="">Барлық оқушы</option>{students.items.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="learning-panel"><h2>Сынып есебі</h2><p>{students.items.length} оқушы · {queue.items.length} тексерілмеген жұмыс</p><div className="table-scroll"><table><thead><tr><th>Оқушы</th><th>Сабақ</th><th>Орташа баға</th><th>Назар қажет</th></tr></thead><tbody>{students.items.map(s=>{const work=all.filter(e=>e.ownerId===s.id&&e.status==='reviewed'&&e.scores.length===4),done=progress.items.filter(p=>p.ownerId===s.id&&p.completed&&course.some(l=>l.id===p.lessonId)).length;return <tr key={s.id}><td><button className="text-button" onClick={()=>setStudent(s.id)}>{s.name}</button></td><td>{done} / {course.length}</td><td>{work.length?(work.reduce((n,e)=>n+(mean(e.scores)||0),0)/work.length).toFixed(1):'Дерек жоқ'}</td><td>{[...new Set(work.flatMap(e=>e.focus||[]))].join(', ')||'Белгіленбеген'}</td></tr>})}</tbody></table></div><p>«Назар қажет» — мұғалім тексеру кезінде белгілеген дағдылар.</p></div></>}
 <div className="dashboard-stats"><div><span>Аяқталған сабақ</span><strong>{completed.length}<small> / {teacher&&!student?course.length*students.items.length:course.length}</small></strong></div><div><span>Тексерілген жұмыс</span><strong>{reviews.length}</strong></div><div><span>Оқу ұпайы</span><strong>{xp} XP</strong></div><div><span>Дұрыс орындалған жаттығу</span><strong>{passed.size}</strong></div></div><p className="muted-text">XP: аяқталған сабақ +10, толық дұрыс жаттығу +10, сақталған толық жоспар +15, жіберілген эссе/қайта жазу +30, финалдық жұмыс +50. Бір жазба қайталап есептелмейді.</p>
 {(!teacher||student)&&<div className="learning-panel course-progress-panel"><div className="course-progress-heading"><div><span>КУРС ПРОГРЕСІ</span><h2>{next?'Оқуды жалғастыр':'Курс аяқталды'}</h2></div><strong>{course.length?Math.round(completed.length/course.length*100):0}%</strong></div>{next&&<p className="course-current">Ағымдағы бөлім: <strong>{next.category}</strong></p>}<div className="course-progress-track" role="progressbar" aria-label="Курс прогресі" aria-valuemin={0} aria-valuemax={course.length||1} aria-valuenow={completed.length}><span style={{width:(course.length?completed.length/course.length*100:0)+'%'}}/></div><div className="course-progress-meta"><span>{completed.length} сабақ аяқталды</span><span>Барлығы {course.length} сабақ</span></div>{!teacher&&next&&<Link className="button" to={'/lessons/'+next.id}>Жалғастыру: {next.number}. {next.title}</Link>}{!teacher&&!diagnostic&&<p><Link to="/practice/course-foundation?lesson=course-01">Бастапқы диагностикалық эссе</Link></p>}<div className="course-badges">{badges.map(b=><span className="tag" key={b}>{b}</span>)}</div></div>}
 <div className="learning-panel skills-panel"><h2>Төрт критерий бойынша нәтиже</h2><div className="criteria-list">{focusNames.map((f,i)=><div className="criterion" key={f}><span>{f}</span><progress max={9} value={criterionMeans[i]||0}/><strong>{criterionMeans[i]?.toFixed(1)||'Баға жоқ'}</strong></div>)}</div>{weakest!==null&&<div className="focus-skill-card"><span className="focus-skill-icon" aria-hidden="true">!</span><div><small>НАЗАР АУДАРАТЫН ДАҒДЫ</small><strong>{focusNames[weakest]}</strong><p>Ұсыныс сақталған мұғалім бағаларының орташа мәніне негізделген.</p></div>{!teacher&&<Link to={'/lessons/'+['course-03','course-07','course-16','course-22'][weakest]}>Дағдыны қайталау →</Link>}</div>}<div className="skill-section-heading"><div><span>01</span><h3>Жеке даму мақсаттары</h3></div><p>Мұғалім ұсынған келесі қадамдар</p></div>{teacher&&!student?<div className="skill-empty">Жеке мақсаттарды көру үшін оқушыны таңдаңыз.</div>:targets.length?<div className="goal-cards">{targets.map((g,i)=><article key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{g}</p></article>)}</div>:<div className="skill-empty">Мұғалім тексерген жұмыстан кейін мақсаттар көрсетіледі.</div>}<div className="skill-section-heading"><div><span>02</span><h3>Тексерулердегі белгілер</h3></div><p>Қай дағды неше жұмыста белгіленді</p></div>{focusCounts.some(Boolean)?<div className="focus-count-grid">{focusNames.map((f,i)=><article className={'focus-count focus-'+i} key={f}><div><span>{f}</span><strong>{focusCounts[i]} <small>жұмыс</small></strong></div><div className="focus-track"><span style={{width:(focusCounts[i]/Math.max(...focusCounts,1)*100)+'%'}}/></div></article>)}</div>:<div className="skill-empty">Мұғалім әлі дағды белгілемеген.</div>}</div>
 <div className="learning-panel"><h2>Баға тарихы</h2>{reviews.length?<div className="table-scroll"><table><thead><tr><th>Жұмыс</th>{focusNames.map(f=><th key={f}>{f}</th>)}</tr></thead><tbody>{reviews.map(e=><tr key={e.id}><td><Link to={'/work/'+e.id}>{e.title} · {e.createdAt?.toDate().toLocaleDateString(localeTag())}</Link></td>{e.scores.map((s,i)=><td key={i}><meter min={0} max={9} value={s}/> {s}</td>)}</tr>)}</tbody></table></div>:<p>Тексерілген жұмыстар жоқ.</p>}</div>
 {(!teacher||student)&&<div className="learning-panel"><h2>Диагностика → финалдық сынақ</h2><p>Бастапқы нәтиже: {diagnostic?score(diagnostic):'Әлі бағаланбаған'} · Финалдық нәтиже: {final?score(final):'Әлі бағаланбаған'}</p>{diagnostic&&final&&<p>Орташа баға өзгерісі: {((mean(final.scores)||0)-(mean(diagnostic.scores)||0)).toFixed(1)}. Бағалар мұғалімнің оқу бағалауы, ресми IELTS нәтижесі емес.</p>}{!teacher&&<Link to="/practice/course-final?lesson=course-34">Финалдық сынаққа өту</Link>}</div>}
 <h2>{teacher?'Жұмыстар мен нұсқалар':'Жазылым портфолиосы'}</h2><div className="course-filters">{[['all','Барлығы'],['draft','Жобалар'],['submitted','Тексеру'],['reviewed','Тексерілген']].filter(([v])=>!teacher||v!=='draft').map(([v,t])=><button key={v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{t}</button>)}</div>{!visible.length&&<p>Әзірге жұмыс жоқ.</p>}{[...groups].map(([root,versions])=>{const shown=versions.filter(e=>filter==='all'||e.status===filter);return shown.length?<div className="learning-panel" key={root}><span className="tag">{prompts.items.find(p=>p.id===versions[0].promptId)?.type||'Жазу жұмысы'}</span><h3>{versions[0].title}</h3>{shown.map(e=><div className="portfolio-row" key={e.id}><Link to={e.status==='draft'?'/practice/'+e.promptId+'?draft='+e.id:'/work/'+e.id}>{teacher?e.studentName+' · ':''}{e.version||1}-нұсқа · {e.status==='draft'?'Жоба':e.status==='submitted'?'Тексеру':'Тексерілген'}</Link><strong>{e.status==='reviewed'?score(e):'Баға жоқ'}</strong></div>)}</div>:null})}<AccountDeletion/></>}</section>
}
