import { useState } from 'react';
import { ArrowRight, RotateCcw, CheckCircle2, XCircle, Trophy } from 'lucide-react';
const questions = [
 {q:'Writing Task 2 эссесінде кемінде қанша сөз жазу керек?',a:['150 сөз','200 сөз','250 сөз','350 сөз'],correct:2,why:'Task 2 үшін кемінде 250 сөз қажет. Ойды толық жеткізіп, тек көлем үшін артық сөйлем қоспа.'},
 {q:'Task 2-ге шамамен қанша уақыт бөлу ұсынылады?',a:['20 минут','30 минут','40 минут','60 минут'],correct:2,why:'Writing бөлігінің 60 минуты ішінде Task 2-ге шамамен 40 минут қалдырған дұрыс.'},
 {q:'«Discuss both views and give your own opinion» нені талап етеді?',a:['Тек өз пікіріңді жазуды','Екі көзқарасты түсіндіріп, өз пікіріңді білдіруді','Тек келіспейтін көзқарасты сынауды','Тақырыпты қысқаша сипаттауды'],correct:1,why:'Сұрақтың барлық бөлігін қамту керек: екі көзқарас та талқыланып, жеке ұстаным анық көрінуі тиіс.'},
 {q:'Thesis statement дегеніміз не?',a:['Кез келген қызықты факт','Мысалдардың тізімі','Эссенің негізгі ұстанымын білдіретін сөйлем','Сөздік анықтамасы'],correct:2,why:'Thesis statement оқырманға негізгі жауабыңды көрсетеді. Ол әдетте кіріспеде беріледі.'},
 {q:'Негізгі абзацты қалай дамыту тиімді?',a:['Ой → түсіндіру → нақты мысал','Көп байланыстырғыш → қысқа қорытынды','Бірнеше қатысы жоқ ой','Тек статистика'],correct:0,why:'Негізгі ойды түсіндіріп, нақты мысалмен қолдау дәлелді дамытады. Мысалдың сұраққа қатысы болуы керек.'},
 {q:'Task Response критерийі негізінен нені бағалайды?',a:['Қолжазбаның әдемілігін','Сұраққа жауап пен идеялардың дамуын','Тек тыныс белгілерін','Тек абзац санын'],correct:1,why:'Task Response тапсырманың қаншалықты толық орындалғанын, ұстанымның анықтығын және идеялардың негізделуін бағалайды.'},
 {q:'Coherence and Cohesion үшін қайсысы маңызды?',a:['Әр сөйлемді Moreover деп бастау','Барлық сөзді күрделі синонимге ауыстыру','Ойдың логикалық реті мен табиғи байланысы','Эссені бір абзацпен жазу'],correct:2,why:'Оқырман ойыңды оңай қадағалауы керек. Байланыстырғыштар логиканы көрсетеді, бірақ оның орнын баспайды.'},
 {q:'«However» сөзін қай жағдайда қолданған дұрыс?',a:['Қарама-қарсы ойды енгізгенде','Мысалды енгізгенде','Бірдей ойды қайталағанда','Кез келген сөйлемнің басында'],correct:0,why:'However қарама-қарсылықты білдіреді. Мысал келтіру үшін for example, нәтижені көрсету үшін therefore қолдануға болады.'},
 {q:'Lexical Resource бағасын жақсартатын тәсіл қайсысы?',a:['Мағынасын білмейтін күрделі сөздер қосу','Бір сөзді әр сөйлемде қайталау','Сөздерді дәл мағынада, дұрыс тіркеспен қолдану','Тек қысқа сөздерді қолдану'],correct:2,why:'Сөздік қордың ауқымымен қатар дәлдігі маңызды. Мысалы, make a decision және develop a skill — табиғи тіркестер.'},
 {q:'Қорытындыда не істеу керек?',a:['Жаңа негізгі аргумент қосу','Негізгі жауапты жинақтап, ұстанымды бекіту','Тапсырма сұрағын толық көшіру','Қатысы жоқ кеңес беру'],correct:1,why:'Қорытынды негізгі жауапты жинақтайды. Бұрын талқыланбаған маңызды аргументті соңында енгізбе.'},
 {q:'«Do the advantages outweigh the disadvantages?» сұрағында не қажет?',a:['Тек артықшылықтарды атау','Екі жағын қарастырып, қайсысы басым екенін негіздеу','Өз пікіріңді білдірмеу','Тек мысалдар тізімін жазу'],correct:1,why:'Outweigh салыстырып бағалауды сұрайды. Артықшылықтар мен кемшіліктерді қарастырып, қай жағы басым екенін дәлелде.'},
 {q:'Эссені соңғы рет тексергенде ең пайдалы әрекет қайсысы?',a:['Барлық сөйлемді ұзартып шығу','Кездейсоқ күрделі сөздер қосу','Сұрақтың барлық бөлігіне жауапты, логиканы және тіл қателерін тексеру','Тек сөз санын көбейту'],correct:2,why:'Өзіндік тексеру мазмұн, ой байланысы, сөз қолданысы және грамматиканы қамтуы керек. Мағынаны бұзатын қателерді алдымен түзет.'},
];
export default function Quiz(){
 const [index,setIndex]=useState(0),[answers,setAnswers]=useState<number[]>([]),[selected,setSelected]=useState<number|null>(null),[checked,setChecked]=useState(false),[finished,setFinished]=useState(false);
 const question=questions[index];const score=answers.reduce((sum,a,i)=>sum+(a===questions[i].correct?1:0),0);
 function check(){if(selected===null||checked)return;setAnswers(old=>[...old,selected]);setChecked(true)}
 function next(){if(index===questions.length-1){setFinished(true);return}setIndex(i=>i+1);setSelected(null);setChecked(false)}
 function restart(){setIndex(0);setAnswers([]);setSelected(null);setChecked(false);setFinished(false)}
 return <section className="container page quiz-page"><div className="page-heading"><div className="eyebrow">БІЛІМІҢДІ БЕКІТ</div><h1>Writing Task 2 квизі</h1><p>12 сұрақ. Әр жауаптан кейін — қысқа түсіндірме.</p></div>{finished?<><div className="quiz-card quiz-finish"><Trophy size={42}/><h2>Квиз аяқталды!</h2><strong className="quiz-score">{score} / {questions.length}</strong><p>{score>=10?'Негіздерді жақсы меңгердің!':score>=6?'Жақсы бастама! Қате жауаптардың түсіндірмесін қайталап шық.':'Түсіндірмелерді оқып, қайта байқап көр. Әр қадам — жаңа білім.'}</p><p className="muted-text">Бұл білімді бекіту нәтижесі, IELTS band бағасы емес.</p><button className="button" onClick={restart}><RotateCcw size={17}/> Қайта өту</button></div><div className="quiz-review">{questions.map((q,i)=><article className="quiz-card" key={q.q}><h3>{answers[i]===q.correct?<CheckCircle2 size={19} className="quiz-good"/>:<XCircle size={19} className="quiz-wrong"/>}{i+1}. {q.q}</h3><p>Сенің жауабың: {q.a[answers[i]]}</p>{answers[i]!==q.correct&&<p><strong>Дұрыс жауап: {q.a[q.correct]}</strong></p>}<p className="muted-text">{q.why}</p></article>)}</div></>:<div className="quiz-card"><div className="quiz-meta"><span>{index+1} / {questions.length} сұрақ</span><span>{score} дұрыс жауап</span></div><progress className="quiz-progress" aria-label="Квиз прогресі" value={answers.length} max={questions.length}/><fieldset className="content-fields" disabled={checked}><legend className="quiz-question">{question.q}</legend><div className="quiz-options">{question.a.map((a,i)=><label key={a} className={'quiz-option '+(selected===i?'selected ':'')+(checked&&i===question.correct?'correct ':checked&&selected===i?'incorrect':'')}><input type="radio" name={'question-'+index} checked={selected===i} onChange={()=>setSelected(i)}/><span>{String.fromCharCode(65+i)}</span><strong>{a}</strong>{checked&&i===question.correct&&<CheckCircle2 size={20}/>}</label>)}</div></fieldset>{checked&&<div className={'notice '+(selected===question.correct?'':'error')} role="status"><strong>{selected===question.correct?'Дұрыс!':'Дұрыс жауап: '+question.a[question.correct]}</strong><p>{question.why}</p></div>}<div className="quiz-actions">{checked?<button className="button" onClick={next}>{index===questions.length-1?'Нәтижені көру':'Келесі сұрақ'}<ArrowRight size={17}/></button>:<button className="button" onClick={check} disabled={selected===null}>Жауапты тексеру <CheckCircle2 size={17}/></button>}</div><p className="quiz-local-note">Прогресс осы бетте ғана сақталады. Бетті жаңартсаң немесе басқа бетке өтсең, квиз қайта басталады.</p></div>}</section>
}
